name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Inject Secret into Environment File
        env:
          githubToken: ${{ secrets.GH_TOKEN }}
        run: |
          ENV_FILE="./src/environments/environment.prod.ts"

          if [ ! -f "$ENV_FILE" ]; then
            echo "Eroare: FiÈ™ierul de mediu $ENV_FILE nu a fost gÄƒsit."
            exit 1
          fi

          TOKEN_ESCAPED=$(echo $githubToken | sed 's/[&/\]/\\&/g')

          sed -i "s|githubToken: '.*'|githubToken: '${TOKEN_ESCAPED}'|" $ENV_FILE

          echo "Secretul a fost injectat Ã®n proprietatea 'githubToken' din $ENV_FILE."

      - name: Build to docs folder
        run: |
          npm install
          npm run build -- --configuration=production --base-href=/

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git commit -m "ðŸš€ Auto-deploy: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
